[project]
name = "marimo-cats"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.4.3",
    "geopandas>=1.1.2",
    "marimo>=0.18.4",
    "pandas>=2.3.3",
    "sqlglot>=28.5.0",
]
